CREATE DATABASE FLORICULTURA;
USE FLORICULTURA;

CREATE TABLE CLIENTE (

COD_CLI INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
NOME_CLIENTE VARCHAR(50),
RG VARCHAR(15),
TELEFONE VARCHAR(15),
ENDERECO VARCHAR (20),
PRIMARY KEY CLIENTE(COD_CLI)

);

CREATE TABLE PEDIDO (

COD_PEDIDO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
DATA_COMPRA DATE,
VALOR_TOTAL DOUBLE,
PRODUTOS_COMPRADOS VARCHAR(40),
PRIMARY KEY PEDIDO(COD_PEDIDO)

);

SELECT * FROM PEDIDO;

-- 1) adicionar o atributo que será FK na tabela pedido
ALTER TABLE PEDIDO ADD  COD_CLI INTEGER UNSIGNED NOT NULL;

-- 2) Adicionar a restrição de FK (estabelecer relacionamento entre tabelas)

ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_COD_CLI FOREIGN KEY(COD_CLI) REFERENCES CLIENTE(COD_CLI);